<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks>net8</TargetFrameworks>
    <IsPackable>false</IsPackable>    
  </PropertyGroup>
  <PropertyGroup>
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Sinks.ColoredConsole" Version="3.0.1" />
  </ItemGroup>  
  <ItemGroup>
    <ProjectReference Include="..\Topshelf.Serilog\Topshelf.Serilog.csproj" />
    <ProjectReference Include="..\Topshelf\Topshelf.csproj" />
  </ItemGroup>
</Project>
