<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8</TargetFrameworks>
  </PropertyGroup>

  <PropertyGroup>
    <PackageTags>Topshelf;Elmah</PackageTags>
    <Description>$(Description)</Description>
  </PropertyGroup>

  <PropertyGroup>
    <DefineConstants>$(DefineConstants);NETCORE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ElmahCore" Version="2.1.2" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="1.0.0" PrivateAssets="All" />    
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Topshelf\Topshelf.csproj" />
  </ItemGroup>
</Project>
